services:
  - type: web
    name: entity-json-server
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: PORT
        generateValue: true
      - key: NODE_ENV
        value: production
